CREATE DATABASE IsletmeDefteri;

GO

USE IsletmeDefteri;

GO

CREATE TABLE Kod
(
ID INT IDENTITY  (1,1),
KODISIM  NVARCHAR(10) NOT NULL,
CONSTRAINT PK_Kod PRIMARY KEY (ID),
CONSTRAINT UC_KODISIM UNIQUE (KODISIM)
)

CREATE TABLE HesapKodlari
(
ID INT IDENTITY (1,1),
HESAPKODUADI NVARCHAR(50),
CONSTRAINT PK_HesapKodlari PRIMARY KEY (ID),
CONSTRAINT UC_HESAPKODUADI UNIQUE (HESAPKODUADI)
)

CREATE TABLE Stoklar
(
ID INT IDENTITY (1,1),
STOKADI NVARCHAR(50) NOT NULL
CONSTRAINT PK_Stoklar PRIMARY KEY (ID),
CONSTRAINT UC_SOKADI UNIQUE (STOKADI)
)

CREATE TABLE Kullanicilar
(
ID INT IDENTITY (1,1),
KULLANICIADI NVARCHAR(10) NOT NULL,
CONSTRAINT PK_Kullanicilar PRIMARY KEY (ID),
CONSTRAINT UC_KULLANICIADI UNIQUE (KULLANICIADI)
)

CREATE TABLE Cari
(
ID INT IDENTITY (1,1),
CARIADI NVARCHAR(50) NOT NULL,
VERGINO CHAR(10) NOT NULL,
CHECK(LEN(VERGINO)=10),
TCNO CHAR(11) NOT NULL,
CHECK(LEN(TCNO)=11),
EMAIIL NVARCHAR(30),
CREATEDDATE DATETIME DEFAULT GETDATE() NOT NULL,
TELNR1 VARCHAR(15),
TELNR2 VARCHAR(15)
CONSTRAINT PK_Cari PRIMARY KEY (ID,VERGINO,TCNO,CARIADI),
CONSTRAINT UC_CARIADI UNIQUE (CARIADI)
)

CREATE TABLE FaturaEkrani
(
ID INT IDENTITY (1,1),
KODID INT FOREIGN KEY REFERENCES Kod(ID),
HESAPKODLARIID INT FOREIGN KEY REFERENCES HesapKodlari (ID),
EVRAKTARIHI DATE NOT NULL,
EVRAKNO NVARCHAR(16),
--CARIADI NVARCHAR(50) FOREIGN KEY Cari(CARIADI),
--CARIID INT FOREIGN KEY REFERENCES Cari(ID) NOT NULL,
--VERGINOIDORTCNOID TINYINT FOREIGN KEY REFERENCES Cari (VERGINO,TCNO),
--VERGINOIDORTCNO TINYINT FOREIGN KEY REFERENCES Cari (TCNO),
CARIADI NVARCHAR(50),
STOKID INT FOREIGN KEY REFERENCES Stoklar(ID) NOT NULL,
KDVORANI TINYINT NOT NULL,
MATRAH DECIMAL NOT NULL,
-- NASIL HESAPLATABÝLÝRÝM
KDVTUTAR DECIMAL NOT NULL,
-- NASIL HESAPLATABÝLÝRÝM
TOPLAMTUTAR DECIMAL NOT NULL,
KULLANICIID INT FOREIGN KEY REFERENCES Kullanicilar(ID),
KAYITTARIHI DATETIME DEFAULT GETDATE() NOT NULL,
CONSTRAINT PK_FaturaEkrani PRIMARY KEY (ID)
)

INSERT INTO Kod VALUES ('MAL'),
                       ('GÝDER'),
					   ('HÝZMET'),
					   ('ÝADE');

INSERT INTO HesapKodlari VALUES ('MAL ALIÞ');
INSERT INTO HesapKodlari VALUES ('ELEKTRÝK GÝDERÝ');
INSERT INTO HesapKodlari VALUES ('PAZARLAMA GÝDERLERÝ');
INSERT INTO HesapKodlari VALUES ('YÖNETÝM GÝDERLERÝ');

INSERT INTO Stoklar VALUES ('BUZDOLABI'),
                           ('TELEVÝZYON'),
						   ('ÇAMAÞIR MAKÝNASI'),
						   ('BULAÞIK MAKÝNASI'),
						   ('YAZILIM EÐÝTÝMÝ');

INSERT INTO Kullanicilar VALUES ('KADÝR'),
                                ('AHMET'),
								('VELÝ');

INSERT INTO Cari  (CARIADI,VERGINO,TCNO) VALUES ('TRENDYOL AS','5555555555','66666666666'),
                                                ('VESTEL LTD','4444444444','88888888888'),
												('KARDEÞLER TÝCARET','2541548951','32598541235'),
												('CODER','9999999999','33333333333');

INSERT INTO FaturaEkrani ( [KODID], [HESAPKODLARIID], [EVRAKTARIHI], [EVRAKNO], [CARIADI], [STOKID], [KDVORANI], [MATRAH], [KDVTUTAR], [TOPLAMTUTAR], [KULLANICIID])
VALUES (1,1,'04-15-2022','GIB2022000000132','KARDEÞLER TÝCARET',1,8,10000,800,10800,1);

INSERT INTO FaturaEkrani ( [KODID], [HESAPKODLARIID], [EVRAKTARIHI], [EVRAKNO], [CARIADI], [STOKID], [KDVORANI], [MATRAH], [KDVTUTAR], [TOPLAMTUTAR], [KULLANICIID])
VALUES (1,2,'05-25-2022','GIB2022000000146','TRENDYOL A.Þ.',2,8,5000,400,5400,1);
INSERT INTO FaturaEkrani ( [KODID], [HESAPKODLARIID], [EVRAKTARIHI], [EVRAKNO], [CARIADI], [STOKID], [KDVORANI], [MATRAH], [KDVTUTAR], [TOPLAMTUTAR], [KULLANICIID])
VALUES (1,1,'07-03-2022','GIB2022000000500','VATAN TÝCARET',3,8,20000,1600,21600,2);
INSERT INTO FaturaEkrani ( [KODID], [HESAPKODLARIID], [EVRAKTARIHI], [EVRAKNO], [CARIADI], [STOKID], [KDVORANI], [MATRAH], [KDVTUTAR], [TOPLAMTUTAR], [KULLANICIID])
VALUES (1,1,'09-15-2022','GIB2022000006525','BURSA MAÐAZA TÝCARET',4,8,21000,1680,22680,1);
INSERT INTO FaturaEkrani ( [KODID], [HESAPKODLARIID], [EVRAKTARIHI], [EVRAKNO], [CARIADI], [STOKID], [KDVORANI], [MATRAH], [KDVTUTAR], [TOPLAMTUTAR], [KULLANICIID])
VALUES (3,1,'10-24-2022','GIB2022000000444','CODER BÝLÝÞÝM',5,8,7000,560,7560,2);

SELECT * FROM FaturaEkrani


												



